### ISSUE TITLE
Update DeveloperForce.Force NuGet version to include refresh token fix

### ISSUE THREAD

**Issue by dagood** [developerforce/visual-studio-tools#10]
[This pull request](https://github.com/developerforce/Force.com-Toolkit-for-NET/pull/117) will fix a problem in the Salesforce Toolkit for .NET where refresh token OAuth flow wouldn't work. The refresh token API URL was wrong, causing an unexpected and unhandled exception in the scaffolded runtime code.

Once the pull request is merged and the new version is deployed to NuGet, we need to update the version referenced here.

**Comment by msimons1** [comment]
This issue was fixed with https://github.com/developerforce/visual-studio-tools/commit/8d2bf434faf96a73f759e102e5d29c007d6e4906
